#!/bin/sh
### BEGIN INIT INFO
# Provides:          livAPIs script
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5 6
# Default-Stop:      0 1
# Short-Description: Starts livAPIs daemon at boot time
# Description:       Enable service provided by livAPIs
### END INIT INFO


# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script livAPIs"
    cd /home/pi/liv/livAPIs
    sudo python livAPIs.py &
    ;;
  stop)
    echo "Stopping script livAPIs"
    sudo pkill -f livAPIs.py
    ;;
  *)
    echo "Usage: /etc/init.d/livAPIs {start|stop}"
    exit 1
    ;;
esac

exit 0
