#!/bin/sh
### BEGIN INIT INFO
# Provides:          livAPIsStart script
# Required-Start:    $all
# Required-Stop:     $sly
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts livAPIsStart daemon at boot time
# Description:       Enable service provided by livAPIs
### END INIT INFO


# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script livAPIsStart"
    cd /home/pi/liv/livAPIs
    sudo python livAPIs.py &
    ;;
  stop)
    echo "Stopping script livAPIsStart"
    sudo pkill -f livAPIs.py
    ;;
  *)
    echo "Usage: /etc/init.d/livAPIsStart {start|stop}"
    exit 1
    ;;
esac

exit 0
