#!/bin/sh
### BEGIN INIT INFO
# Provides:          livDemo
# Required-Start:    $all
# Required-Stop:     $sll
# Default-Start:     2 3 4 5 6
# Default-Stop:      0 1
# Short-Description: Starts livDemo daemon at boot time
# Description:       Enable service provided by livDemo
### END INIT INFO


# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script livDemo"
    cd /home/pi/liv
    sudo python livDemo.py &
    ;;
  stop)
    echo "Stopping script livDemo"
    sudo pkill -f livDemo.py
    ;;
  *)
    echo "Usage: /etc/init.d/livDemo {start|stop}"
    exit 1
    ;;
esac

exit 0
