#!/bin/sh
### BEGIN INIT INFO
# Provides:          livXMPPStart script
# Required-Start:    $all
# Required-Stop:     $sly
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts livXMPPStart daemon at boot time
# Description:       Enable service provided by livXMPP
### END INIT INFO


# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script livXMPPStart"
    cd /home/pi/liv/livXMPP
    sudo python xmppLiv.py &
    ;;
  stop)
    echo "Stopping script livXMPPStart"
    sudo pkill -f xmppLiv.py
    ;;
  *)
    echo "Usage: /etc/init.d/livXMPPStart {start|stop}"
    exit 1
    ;;
esac

exit 0
