#!/bin/sh
### BEGIN INIT INFO
# Provides:          livXMPP
# Required-Start:    $all
# Required-Stop:     $sly
# Default-Start:     2 3 4 5 6
# Default-Stop:      0 1
# Short-Description: Starts livXMPP daemon at boot time
# Description:       Enable service provided by livXMPP
### END INIT INFO


# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script livXMPP"
    cd /home/pi/liv/livXMPP
    sudo python livXMPP.py &
    ;;
  stop)
    echo "Stopping script livXMPP"
    sudo pkill -f livXMPP.py
    ;;
  *)
    echo "Usage: /etc/init.d/livXMPP {start|stop}"
    exit 1
    ;;
esac

exit 0
